### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by CihanSari** [s9w/binary_bakery#2]
Great idea! I didn't come across something very similar -- although Qt is cross platform, it is definitely extremely heavy.

I have a few questions
1- Your project seems to be based on visual studio, why not port it to CMake?
2- Is the project (binary file) windows dependent or do you only serve the executable for windows and ask others to compile it for unix/macos?
3- Would you be interested in extending this to make it integrated via CMake to allow resource files to be updated when they change on pre-built steps?

**Comment by CihanSari** [comment]
Hi Sebastian,

1- There were a few changes required, especially on includes and relatively new (c++20 / experimental) stl features but nothing major. I could get the code to compile and vast majority of tests to pass on Ubuntu.

2- All dependencies can be compiled using vcpkg. Instructions that I used for them are provided within the PR.

You can find my PR here: https://github.com/s9w/binary_bakery/pull/3

**Comment by s9w** [comment]
Hey wow, thanks for that - a lot! Two things:
1) What's with the changes from the ui8 literals to `static_cast<uint8_t>(0)` etc? Style, compiler differences or something else?
2) I'm going to need to get some familiarity with cmake. Some things are pretty wild. I did manage to compile it with your instructions though. Out of curiosity, I tried loading it with Visual Studios cmake support. That did not work out, log:

```
1> [CMake] CMake Error at C:/inc/vcpkg-master/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "lz4" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     lz4Config.cmake
1> [CMake]     lz4-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "lz4" to CMAKE_PREFIX_PATH or set "lz4_DIR"
1> [CMake]   to a directory containing one of the above files.  If "lz4" provides a
1> [CMake]   separate development package or SDK, be sure it has been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   binary_bakery_lib/CMakeLists.txt:23 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
```

Not sure what to make of it or if  that's relevant.

**Comment by CihanSari** [comment]
Of course mate, take your time :).

I would like to add cmake scripts to consume this library inside cmake and generate/compress resource files associated with the project and generate the header files. Add these into a cmake target (optionally as dynamic or static) and provide the content to the projects which depend on it to fully automate resource file generation.

I am not sure when I can look into this yet or how this plays into your plans of the library.

**Comment by saxbophone** [comment]
This is an exciting discussion. I too am interested in trying this out on Unix with CMake. If it would be useful to keep track of whether this project builds cross-platform, I've had some success using Github Actions to compile the code for multiple platforms with CMake. Ask me if you want some pointers on how that might be done (building and testing on CI is easier when your dependencies are trivial, I must admit).

**Comment by CihanSari** [comment]
I think testing on unix & windows should not be too hindered with the PR's build instructions (using vcpkg for the dependencies cross platform).

I would wait until my PR matures and gets merged or work on my fork to automate the tests.

Regarding this, we should add tests to cmake as tests (currently they are executable) and allow it to be run using CTest for an easier time.

Would you be interested in working on it @saxbophone ?

**Comment by saxbophone** [comment]
> Regarding this, we should add tests to cmake as tests (currently they are executable) and allow it to be run using CTest for an easier time.
> Would you be interested in working on it @saxbophone ?
I'm not in a position to write any unit tests but I am happy to share the workflow I use for cross-platform unit-testing. To be honest, I was thinking more about basic testing that the project compiles cross-platform when I wrote my comments, but if you have unit tests that can be integrated, that would be great.

**Comment by saxbophone** [comment]
@CihanSari With CMake, you can choose to add an executable target as a test case. I think it's the `add_test()` function. This integrates with CTest so your current process of using an executable for the tests can be maintained, just `enable_testing()` and some calls to `add_test()`.

**Comment by saxbophone** [comment]
@CihanSari With CMake, you can choose to add an executable target as a test case. I think it's the `add_test()` function. This integrates with CTest so your current process of using an executable for the tests can be maintained, just `enable_testing()` and some calls to `add_test()`.

**Comment by saxbophone** [comment]
For the Github-Actions stuff, I have some samples here for using GHA to run unit tests on every PR and commit merged into master, and also for making release builds for every published release: https://github.com/saxbophone/CPP20-Cross-Platform-Template/tree/master/.github/workflows

In my sample, I build and test with g++ and clang++ on Linux and macOS and with MSVC on Windows.
For the release builds, just one compiler per OS is used (g++ on Linux, clang++ on macOS and MSVC on Windows).

Hopefully a lot of the steps in those build files will be applicable to this project
